// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/hi20160616/spamkiller/configs"
)

// Injectors from wire.go:

func InitializeMails(ctx context.Context, projectName string) (*Mails, error) {
	config := configs.NewConfig(projectName)
	logger, err := NewLog(config)
	if err != nil {
		return nil, err
	}
	mails := NewMails(ctx, config, logger, projectName)
	return mails, nil
}
